name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions #Run Name
on: [push]
jobs:
  job1:                                                  #Job Name
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4
      - run: echo
      - name: Run Code build 1                            #For display
        run: echo
      - run: echo
        name: Run Code Test
      - run: echo
        name: Run Code Review
      - run: echo
        name: Run Code Release
